### PR TITLE
building 20210325 with centos7 + MacOS ARM64

### PR DESCRIPTION
**Pull request by ngam**
- The other pr is taking too long for some reason for ppc and aarch64... maybe cos7 will help? let's see...
- Also adding MACOS ARM64

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
Hi @xhochy could you help me make sure this is set up correctly? https://github.com/ngam/texlive-core-feedstock/blob/ngam20210325/recipe/conda_build_config.yaml#L2

Basically, we have to have 11+ for OSX_ARM64 and I am not sure if the problem still persists in OSX_64. So I wernt for this but not really sure if this works... 
```
# texlive doesn't compile with clang=11 due to the use of multiple function definitions
c_compiler_version:    # [osx]
- '10'                 # [osx_64]
- '11'                 # [osx_arm64]
cxx_compiler_version:  # [osx]
- '10'                 # [osx_64]
- '11'                 # [osx_arm64]
```

**Comment by ngam** [comment]
Probably, let's close this for now and revisit after the regular build is done and merged. There is an error that may require a bit more work:

```
checking for Object::initCmd(const char*) etc... no
checking for tangle... no
configure: error: tangle was not found but is required when cross-compiling.
  Install tangle or set $TANGLEBOOT to the full pathname.
=== configuring in web2c failed
```

**Comment by xhochy** [comment]
> Hi @xhochy could you help me make sure this is set up correctly? https://github.com/ngam/texlive-core-feedstock/blob/ngam20210325/recipe/conda_build_config.yaml#L2
> 
> Basically, we have to have 11+ for OSX_ARM64 and I am not sure if the problem still persists in OSX_64. So I wernt for this but not really sure if this works...
> 
> ```
> # texlive doesn't compile with clang=11 due to the use of multiple function definitions
> c_compiler_version:    # [osx]
> - '10'                 # [osx_64]
> - '11'                 # [osx_arm64]
> cxx_compiler_version:  # [osx]
> - '10'                 # [osx_64]
> - '11'                 # [osx_arm64]
> ```
> 
> updated to:
> 
> ```
> # texlive doesn't compile with clang=11 due to the use of multiple function definitions
> c_compiler_version:    # [osx_64]
> - '10'                 # [osx_64]
> cxx_compiler_version:  # [osx_64]
> - '10'                 # [osx_64]
> 
> # clang=11 is the earliest available for osx_arm64
> c_compiler_version:    # [osx_arm64]
> - '11'                 # [osx_arm64]
> cxx_compiler_version:  # [osx_arm64]
> - '11'                 # [osx_arm64]
> ```

That looks quite good but I haven't seen the selectors used here before.

**Pull request closed without merging**
