### PR TITLE
Add aarch64

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
Needs https://github.com/conda-forge/poppler-feedstock/commit/bd3ac5d792b582a3b1117ee37faaf709ea38840b

**Comment by hmaarrfk** [comment]
https://github.com/conda-forge/poppler-feedstock/pull/52

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
build number bumped because ppc64le package was built using dependencies from defaults.

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
Closes #28 
Closes#26

**Comment by jayfurmanek** [comment]
Great cleanup! Thanks @hmaarrfk !

**Comment by jayfurmanek** [comment]
@ocefpaf  This is a good one to merge, I think. Not only does it add aarch64, but it cleans up the rest of the dependencies we've been struggling with with this recipe.

**Comment by ocefpaf** [comment]
Thanks @hmaarrfk for the PR and @jayfurmanek for the review!

**Pull request merged**
