### PR TITLE
Build OSX (Pt. 2)

### PR DESCRIPTION
**Pull request by jakirkham**
Trying a tweak to see if we can build on OS X with this. I based this off of your PR ( https://github.com/conda-forge/texlive-core-feedstock/pull/2 ), @ocefpaf. Hope that is ok.

### CODE REVIEW

**Comment by jakirkham** [comment]
So, this worked for me locally. Let's see if it passes on Travis CI. Also, please share your thoughts on this.

**Comment by jakirkham** [comment]
Appears it passes on Travis CI too. 😄

**Comment by jakirkham** [comment]
Could you please look at this when you have a chance, @ocefpaf?

**Comment by ocefpaf** [comment]
LGTM

**Comment by jakirkham** [comment]
Thanks @ocefpaf.

**Pull request merged**
