### PR TITLE
update recipe

### PR DESCRIPTION
**Pull request by jayfurmanek**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

OK, Let's update TexLive. This one is a bit of a mess, but this PR will get the 2018 version built. It has the same limitations as before. This grafts parts of Anaconda's latest recipe including the disablement of the unit tests due to two failing on Linux. The test runs fine manually.

This also enables multi-arch builds on ppc64le. (attempted aarch64, but CDT packages are needed)

https://github.com/conda-forge/texlive-core-feedstock/issues/29

### CODE REVIEW

**Comment by jayfurmanek** [comment]
@conda-forge-admin, please rerender

**Comment by jayfurmanek** [comment]
@conda-forge-admin, please rerender

**Comment by jayfurmanek** [comment]
@conda-forge-admin, please rerender

**Comment by jayfurmanek** [comment]
@conda-forge-admin, please rerender

**Comment by jayfurmanek** [comment]
@mariusvniekerk @ocefpaf I think this is ready?

**Comment by mariusvniekerk** [comment]
This is awesome.  Pity about some of the upstream version constraints.

**Comment by mariusvniekerk** [comment]
Could you try to remove all the version pins and use the conda-forge pinnings (aka just rerender since that might work.

**Comment by jayfurmanek** [comment]
Thanks @mariusvniekerk . I think I tried that (I will try again to be sure). I was having some problems since some of the deps come from defaults on ppc64le.  I'll give it a shot to see.

**Comment by jayfurmanek** [comment]
poppler for sure needs to be 0.64 or 0.65 - The included patch doesn't work otherwise.

**Comment by ocefpaf** [comment]
Thanks for working on this!

@jayfurmanek is this ready for a review and merge?
@mariusvniekerk any more comments?

**Comment by mariusvniekerk** [comment]
@ocefpaf None from me aside from the already mentioned one

**Comment by jayfurmanek** [comment]
It's almost ready. I want to try the suggestion from @mariusvniekerk to try and ease up on the dep restrictions. Other than that, though, shouldn't be any other changes.

**Comment by ocefpaf** [comment]
Awesome! Thanks again for working on this!

**Comment by jayfurmanek** [comment]
@conda-forge-admin, please rerender

**Comment by jayfurmanek** [comment]
OK. I removed most of the pins. Poppler needs to stay at the 0.64 or 0.65 though and that pulls a few others down as well. This is better than before though. Should be ready to go!

**Comment by ocefpaf** [comment]
Looks like only `harfbuzz` and `poppler`. Why is the old `poppler` needed? A problem with the packages or limitation of `texlive-core`? If we cannot unpin it in the near future we can try to rebuild the old `poppler` with a newer `harfbuzz` to make it easier to install it.

BTW, merging this and any extra work to unpin can be done in a newer PR. Just is a great start already. Thanks @jayfurmanek!

**Pull request merged**
