### PR TITLE
Build long prefix package and update to 20160523b

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by jakirkham** [comment]
I think we need to update the pinnings. Here is an old pinning PR ( https://github.com/conda-forge/texlive-core-feedstock/pull/7 ), but I think it is even out-of-date. Maybe worth checking this against the wiki.

**Comment by ocefpaf** [comment]
Thanks @jjhelmus!

**Comment by jakirkham** [comment]
Appears the tests did not run on CircleCI. 😕 As a result, it appears to now fail on `master` as we have some dependencies not rebuilt with `conda-build` 2 yet.

```
Adding distribution /feedstock_root/build_artefacts/linux-64/texlive-core-20160523b-pl5.20.3.1_0.tar.bz2 to conda-forge's main channel
Packages with binary prefixes shorter than 255 characters:
/feedstock_root/build_artefacts/linux-64/texlive-core-20160523b-pl5.20.3.1_0.tar.bz2 (80 chars)

./ci_support/run_docker_build.sh returned exit code 1
```

**Comment by jakirkham** [comment]
Seems to be `fontconfig` that is the issue.

xref: https://github.com/conda-forge/conda-forge-build-setup-feedstock/issues/40#issuecomment-265469774

**Comment by jakirkham** [comment]
Restarting now that `fontconfig` version `2.11.`` is rebuilt.

**Comment by jakirkham** [comment]
`texlive` has now been rebuilt successfully.

**Pull request merged**
