### PR TITLE
Add minimal-example tests for pdflatex and latex

### PR DESCRIPTION
**Pull request by willirath**
This will try to compile a minimal LaTeX document with `pdflatex` and `latex`.  With the current master branch, it will probably fail.

### CODE REVIEW

**Comment by nsoranzo** [comment]
Maybe the tests could be added instead of substituting the `--version` tests.

**Comment by willirath** [comment]
This would help differentiate the problem into:

- The `latex` and `pdflatex` symlinks are there.
- But they can't compile a LaTeX file.

**Comment by nsoranzo** [comment]
Thanks @willirath!

**Comment by bgruening** [comment]
@conda-forge-admin, please rerender

**Pull request closed without merging**
